"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Defínela en tu .env; este valor solo es un respaldo para desarrollo local.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-0c@-v4#bo+rj-&hx_l7c0cf502-wyn$yv(r*kxg5+^u6lhjh-g'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'axes',
    'tickets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tickets.middleware.TimezoneMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tickets.context_processors.permisos',
                'tickets.context_processors.version',
                'tickets.context_processors.textos',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Por default usa SQLite (ideal para desarrollo local). Para producción con
# PostgreSQL, define DB_ENGINE=postgresql y el resto de las variables DB_* en el .env.

if os.environ.get('DB_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos que se guardan en el propio servidor (ej. logos de empresa), no en Cloudinary
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Archivos subidos por usuarios (imágenes de tickets) -> Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}
STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
# django-cloudinary-storage todavía revisa este ajuste "clásico" (pre-STORAGES) en su
# propio comando collectstatic; debe coincidir con STORAGES['staticfiles']['BACKEND'].
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Envío de correos (aviso de cierre de tickets) vía Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_BCC_CIERRE = os.environ.get('EMAIL_BCC_CIERRE')

# Liga pública donde vive el sistema (usada en correos, ej. bienvenida)
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# Cuenta de administrador protegida: se crea sola después de cada `migrate` si no existe
# (ver tickets/apps.py). Nunca se hardcodea aquí; vive únicamente en el .env de cada instalación.
ADMIN_PROTEGIDO_USERNAME = os.environ.get('ADMIN_PROTEGIDO_USERNAME')
ADMIN_PROTEGIDO_EMAIL = os.environ.get('ADMIN_PROTEGIDO_EMAIL', '')
ADMIN_PROTEGIDO_TELEFONO = os.environ.get('ADMIN_PROTEGIDO_TELEFONO', '')
ADMIN_PROTEGIDO_PASSWORD = os.environ.get('ADMIN_PROTEGIDO_PASSWORD')

# Textos personalizables del sistema (se muestran en el header y en inicio)
NOMBRE_SISTEMA = os.environ.get('NOMBRE_SISTEMA', 'Atención al Cliente')
TEXTO_SELECCION_EMPRESA = os.environ.get('TEXTO_SELECCION_EMPRESA', 'Selecciona una empresa')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'inicio'
LOGOUT_REDIRECT_URL = 'inicio'
LOGIN_URL = 'login'

AUTH_USER_MODEL = 'tickets.Usuario'

# La sesión expira al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Además, expira después de cierto tiempo de inactividad (en segundos)
SESSION_COOKIE_AGE = 1800  # 30 minutos, ajústalo a lo que prefieras

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # debe ir primero: bloquea antes de intentar autenticar
    'tickets.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',  # dejamos el original también, por si acaso
]

# django-axes: bloqueo por fuerza bruta en el login.
# Las contraseñas son un PIN de 4 dígitos (10,000 combinaciones), así que un
# límite bajo de intentos es importante.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = 'tickets/bloqueado.html'
