# Generated by Django 5.2.15 on 2026-07-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='tickets.empresa'),
        ),
    ]
