# Generated by Django 5.2.15 on 2026-07-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contacto_alternativo',
            field=models.CharField(blank=True, help_text='Opcional: otro dato de contacto por si no logramos localizarte con el principal', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dato_contacto',
            field=models.CharField(default='sin dato', help_text='Número de teléfono, correo o WhatsApp según lo seleccionado', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='medio_contacto',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('correo', 'Correo electrónico'), ('whatsapp', 'WhatsApp')], default='correo', max_length=10),
            preserve_default=False,
        ),
    ]
