# Generated by Django 5.2.15 on 2026-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_contacto_alternativo_ticket_dato_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agente', 'Agente'), ('soporte', 'Agente de Soporte'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
    ]
