# Generated by Django 5.2.15 on 2026-07-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='evidencia_resolucion',
            field=models.TextField(blank=True, help_text='Detalle de lo que se hizo para resolver o avanzar el ticket'),
        ),
    ]
