# Generated by Django 5.2.15 on 2026-07-03 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketactualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
