# Generated by Django 5.2.15 on 2026-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_cerrado_por_ticket_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
