# Generated by Django 5.2.15 on 2026-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_empresa_eliminada_empresa_fecha_eliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requiere_atencion',
            field=models.BooleanField(default=False),
        ),
    ]
