# Generated by Django 5.2.15 on 2026-07-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_requiere_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tickets/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tickets.ticketactualizacion')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Imagen de ticket',
                'verbose_name_plural': 'Imágenes de tickets',
            },
        ),
    ]
