# Generated by Django 5.2.15 on 2026-07-04 20:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticketimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_limite_confirmacion',
            field=models.DateTimeField(blank=True, help_text='Si no hay confirmación del cliente antes de esta fecha, el ticket se cierra automáticamente', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='motivo_cierre',
            field=models.CharField(blank=True, choices=[('cliente', 'Confirmado por el cliente'), ('automatico', 'Cierre automático (sin respuesta)')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pdf_cierre',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cierres/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('pendiente_confirmacion', 'Pendiente de confirmación'), ('cerrado', 'Cerrado')], default='abierto', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketactualizacion',
            name='estado_en_ese_momento',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('pendiente_confirmacion', 'Pendiente de confirmación'), ('cerrado', 'Cerrado')], max_length=25),
        ),
    ]
