# Generated by Django 5.2.15 on 2026-07-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_fecha_limite_confirmacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agente', 'Agente Cliente'), ('soporte', 'Agente de Soporte'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
    ]
