# Generated by Django 5.2.15 on 2026-07-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_usuario_telefono_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('agente', 'Agente Cliente'), ('soporte', 'Agente de Soporte'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
    ]
