# Generated by Django 5.2.15 on 2026-07-09 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cliente_eliminado_nombre',
            field=models.CharField(blank=True, help_text='Nombre de usuario guardado si el cliente fue eliminado permanentemente', max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='motivo_cierre',
            field=models.CharField(blank=True, choices=[('cliente', 'Confirmado por el cliente'), ('automatico', 'Cierre automático (sin respuesta)'), ('eliminacion_usuario', 'Cerrado por eliminación de usuario')], max_length=20, null=True),
        ),
    ]
