# Generated by Django 5.2.15 on 2026-07-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_ticket_cliente_eliminado_nombre_alter_ticket_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='protegido',
            field=models.BooleanField(default=False, help_text='Cuenta del sistema que no se puede desactivar, restablecer ni eliminar desde la interfaz'),
        ),
    ]
