# Generated by Django 5.2.15 on 2026-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_usuario_protegido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketimagen',
            name='imagen',
            field=models.FileField(upload_to='tickets/'),
        ),
    ]
