# Generated by Django 5.2.15 on 2026-07-10 08:50

import tickets.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticketimagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketimagen',
            name='nombre_original',
            field=models.CharField(blank=True, help_text='Nombre del archivo tal como lo subió el usuario (Cloudinary no conserva la extensión)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketimagen',
            name='imagen',
            field=models.FileField(storage=tickets.storage.AdjuntoTicketStorage(), upload_to='tickets/'),
        ),
    ]
