# Generated by Django 5.2.15 on 2026-07-10 08:57

import tickets.models
import tickets.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticketimagen_nombre_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketimagen',
            name='imagen',
            field=models.FileField(storage=tickets.storage.AdjuntoTicketStorage(), upload_to=tickets.models.ruta_adjunto_ticket),
        ),
    ]
