# Generated by Django 5.2.15 on 2026-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_ticketimagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requiere_atencion_cliente',
            field=models.BooleanField(default=False, help_text='True cuando soporte agregó una actualización que el cliente todavía no ha visto'),
        ),
    ]
