# Generated by Django 5.2.15 on 2026-07-10 14:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ticket_requiere_atencion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Se guarda en el propio servidor (no en Cloudinary), ya que son pocas imágenes y ligeras', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='empresas/'),
        ),
    ]
