# Generated by Django 5.2.15 on 2026-07-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='empresa_eliminada_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la empresa guardado si fue eliminada permanentemente', max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.empresa'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='motivo_cierre',
            field=models.CharField(blank=True, choices=[('cliente', 'Confirmado por el cliente'), ('automatico', 'Cierre automático (sin respuesta)'), ('eliminacion_usuario', 'Cerrado por eliminación de usuario'), ('eliminacion_empresa', 'Cerrado por eliminación de empresa')], max_length=20, null=True),
        ),
    ]
